if (FML.isModLoaded("TConstruct") && Tcon_enabled) {
    NEI.hide("TConstruct:Pattern");
    NEI.hide("TConstruct:buckets");
    NEI.hide("TConstruct:woodPattern");
    NEI.override("TConstruct:GlassBlock.StainedClear", [0]);
    NEI.override("TConstruct:GlassPaneClearStained", [0]);
    NEI.override("TConstruct:ToolForgeBlock", [0]);
    NEI.override("TConstruct:ToolStationBlock", [0, 1, 5, 10]);
    NEI.hide("TConstruct:ArrowAmmo");
    NEI.hide("TConstruct:BattleSignBlock");
    NEI.hide("TConstruct:BoltAmmo");
    NEI.hide("TConstruct:Boneana");
    NEI.hide("TConstruct:Crossbow");
    NEI.hide("TConstruct:HeldItemBlock");
    NEI.hide("TConstruct:Javelin");
    NEI.hide("TConstruct:LongBow");
    NEI.hide("TConstruct:ShortBow");
    NEI.hide("TConstruct:Shuriken");
    NEI.hide("TConstruct:ThrowingKnife");
    NEI.hide("TConstruct:battleaxe");
    NEI.hide("TConstruct:battlesign");
    NEI.hide("TConstruct:broadsword");
    NEI.hide("TConstruct:chisel");
    NEI.hide("TConstruct:cleaver");
    NEI.hide("TConstruct:cutlass");
    NEI.hide("TConstruct:dagger");
    NEI.hide("TConstruct:excavator");
    NEI.hide("TConstruct:frypan");
    NEI.hide("TConstruct:hammer");
    NEI.hide("TConstruct:hatchet");
    NEI.hide("TConstruct:longsword");
    NEI.hide("TConstruct:lumberaxe");
    NEI.hide("TConstruct:mattock");
    NEI.hide("TConstruct:pickaxe");
    NEI.hide("TConstruct:rapier");
    NEI.hide("TConstruct:scythe");
    NEI.hide("TConstruct:shovel");
    NEI.override("TConstruct:creativeModifier", [0]);
}
