if (FML.isModLoaded("chisel")) {
    NEI.hide("chisel:*_planks");
    NEI.hide("chisel:*slab_top");
    NEI.hide("chisel:aluminum_stairs.*");
    NEI.hide("chisel:aluminumblock");
    NEI.hide("chisel:amber");
    NEI.hide("chisel:arcane");
    NEI.hide("chisel:beacon");
    NEI.hide("chisel:bookshelf");
    NEI.hide("chisel:brickCustom");
    NEI.hide("chisel:bronzeblock");
    NEI.hide("chisel:cobblestone");
    NEI.hide("chisel:copperblock");
    NEI.hide("chisel:diamond_block");
    NEI.hide("chisel:dirt");
    NEI.hide("chisel:emerald_block");
    NEI.hide("chisel:factoryblock2");
    NEI.hide("chisel:futuraCircuit");
    NEI.hide("chisel:glass");
    NEI.hide("chisel:glass2");
    NEI.hide("chisel:glass_pane");
    NEI.hide("chisel:glowstone");
    NEI.hide("chisel:gold2");
    NEI.hide("chisel:gold_block");
    NEI.hide("chisel:ice");
    NEI.hide("chisel:ice_stairs.*");
    NEI.hide("chisel:iron2");
    NEI.hide("chisel:iron_bars");
    NEI.hide("chisel:iron_block");
    NEI.hide("chisel:jackolantern*");
    NEI.hide("chisel:lapis_block");
    NEI.hide("chisel:leadblock");
    NEI.hide("chisel:limestone_stairs.*");
    NEI.hide("chisel:marble_stairs.*");
    NEI.hide("chisel:mossy_cobblestone");
    NEI.hide("chisel:nation");
    NEI.hide("chisel:nether_brick");
    NEI.hide("chisel:netherrack");
    NEI.hide("chisel:obsidian*");
    NEI.hide("chisel:packedice");
    NEI.hide("chisel:packedice_stairs.*");
    NEI.hide("chisel:pumpkin*");
    NEI.hide("chisel:redstone_block");
    NEI.hide("chisel:sand_snakestone");
    NEI.hide("chisel:sandstone*");
    NEI.hide("chisel:silverblock");
    NEI.hide("chisel:stained_glass_*");
    NEI.hide("chisel:steelblock");
    NEI.hide("chisel:stonebricksmooth");
    NEI.hide("chisel:tallow");
    NEI.hide("chisel:technical2");
    NEI.hide("chisel:thaumium");
    NEI.hide("chisel:tinblock");
    NEI.hide("chisel:torch*");
    NEI.hide("chisel:uraniumblock");
    NEI.hide("chisel:voidstoneRunic");
    NEI.override("chisel:andesite", [0]);
    NEI.override("chisel:antiBlock", [0]);
    NEI.override("chisel:bloodRune", [0]);
    NEI.override("chisel:bone", [0]);
    NEI.override("chisel:carpet", [0]);
    NEI.override("chisel:carpet_block", [0]);
    NEI.override("chisel:cloud", [0]);
    NEI.override("chisel:concrete", [0]);
    NEI.override("chisel:diorite", [0]);
    NEI.override("chisel:factoryblock", [0]);
    NEI.override("chisel:fantasyblock", [0]);
    NEI.override("chisel:fantasyblock2", [0]);
    NEI.override("chisel:futura", [0]);
    NEI.override("chisel:futuraCircuit", [0]);
    NEI.override("chisel:granite", [0]);
    NEI.override("chisel:grimstone", [0]);
    NEI.override("chisel:hexLargePlating", [0]);
    NEI.override("chisel:hexPlating", [0]);
    NEI.override("chisel:holystone", [0]);
    NEI.override("chisel:ice_pillar", [0]);
    NEI.override("chisel:laboratoryblock", [0]);
    NEI.override("chisel:lavastone", [0]);
    NEI.override("chisel:leaves", [7]);
    NEI.override("chisel:limestone", [0]);
    NEI.override("chisel:limestone_slab", [0]);
    NEI.override("chisel:marble", [0]);
    NEI.override("chisel:marble_pillar", [0]);
    NEI.override("chisel:marble_pillar_slab", [0]);
    NEI.override("chisel:marble_slab", [0]);
    NEI.override("chisel:mossy_templeblock", [0]);
    NEI.override("chisel:packedice_pillar", [0]);
    NEI.override("chisel:paperwall", [0]);
    NEI.override("chisel:paperwall_block", [0]);
    NEI.override("chisel:present", [0]);
    NEI.override("chisel:rebel", [0]);
    NEI.override("chisel:road_line", [0]);
    NEI.override("chisel:scorching", [0]);
    NEI.override("chisel:technical", [0]);
    NEI.override("chisel:templeblock", [0]);
    NEI.override("chisel:tyrian", [0]);
    NEI.override("chisel:valentines", [0]);
    NEI.override("chisel:voidstone", [0]);
    NEI.override("chisel:voidstone2", [0]);
    NEI.override("chisel:warningSign", [0]);
    NEI.override("chisel:waterstone", [0]);
    NEI.override("chisel:woolen_clay", [0]);
}
